### PR TITLE
fix: bumps next.js in service/package.json to sync with package.json

### LINKED ISSUE #157: PR140 degrades ozone container
ozone container cannot work after #140 merged.
container raises internal server error when it got request (for login form).

the reason is next,js version mismatched between REPO_ROOT/package.json and  service/package.json

REPO_ROOT/package.json uses new next.js (14.2.5) with new parameter in next.config.js but service/package.json uses older version.

### PR DESCRIPTION
**Pull request by itaru2622**
close #157

### CODE REVIEW

**Comment by itaru2622** [comment]
@foysalit @bnewbold Could you review this PR and merge to get ozone container workable?

**Comment by foysalit** [comment]
our next distro release will cover this. already have a PR waiting on review https://github.com/bluesky-social/ozone/pull/156/files

**Comment by itaru2622** [comment]
@foysalit thank you response. ok I will close this PR when #156 merged.

**Comment by foysalit** [comment]
hey @itaru2622 thanks for reporting these. the latest main should have all of these issues resolved. please feel free to reopen if you se further issues.

**Pull request closed without merging**
